# This file is a template, and might need editing before it works on your project.
image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/ds_2/go-support-lib
include:
  - project: 'ds_2/ci-templates'
    ref: v0.1.4 # you can also use the branch name, or a SHA256 value
    file: # you can add multiple files you need for your project
      - '/templates/stages.yaml'
      - '/templates/build-golang.yaml'
