# This file is a template, and might need editing before it works on your project.
image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/ds_2/go-support-lib
  GOLANG_BEFORE_SCRIPT: "chmod a+x ci.sh; ./ci.sh"
  CI: "1"

include:
  - project: 'ds_2/ci-templates'
    ref: develop
    file:
      - '/templates/stages.yaml'
      - '/templates/build-golang.yaml'
