image: golang:latest

variables:
  REPO_NAME: gitlab.com/ds_2/go-support-lib
  CI: "1"

include:
  - project: 'ds_2/ci-templates'
    ref: v0.1.17
    file:
      - '/templates/stages.yaml'
      - '/templates/build-golang.yaml'
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
