header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Dirk Strauss

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - '**/*.proto'
    - '**/*.pb.go'
    - 'go.mod'
    - 'go.sum'
    - 'LICENSE'
    - 'NOTICE'
    - '.github'
    - '.*'

  comment: on-failure

dependency:
  files:
    - go.mod