# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# To apply it:
# touch .pre-commit-config.yaml
# pre-commit autoupdate
# pre-commit install --allow-missing-config
# pre-commit run --all-files
exclude: "^$"
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-case-conflict
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: detect-aws-credentials
      - id: check-ast
      - id: mixed-line-ending
        args: [--fix=lf]
