/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

plugins {
    id("net.researchgate.release") version "2.8.1"
    id("com.pivotstir.gogradle") version "1.1.5"
}

extensions.getByType(com.pivotstir.gogradle.GoPluginExtension::class).apply {
    env {
        version = "1.14"
        useSandbox = false
    }

    build {
        packagePaths = listOf("./...")
    }

    dep {
        thirdpartyIgnored = true
    }

    dependencies {
        build("github.com/golang/protobuf@v1.4.2")
        test("github.com/stretchr/testify@v1.5.1")
    }
}

tasks.register<com.pivotstir.gogradle.tasks.GoBuild>("build") {
    group = "Build"
    description = "Dummy mirror for goBuild"
    doLast {
        println("Hello, World!")
    }
}

tasks.register<com.pivotstir.gogradle.tasks.GoClean>("clean") {
    group = "Build"
    description = "Dummy mirror for goClean"
}

release {
}
