// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package sysinfo is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	PartitionInfo
	HostInfo
	HealthInfo
*/
package sysinfo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PartitionInfo struct {
	MountPath string `protobuf:"bytes,1,opt,name=MountPath" json:"MountPath,omitempty"`
	Size      uint64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Free      uint64 `protobuf:"varint,3,opt,name=free" json:"free,omitempty"`
	FsType    string `protobuf:"bytes,4,opt,name=fsType" json:"fsType,omitempty"`
	Device    string `protobuf:"bytes,5,opt,name=device" json:"device,omitempty"`
}

func (m *PartitionInfo) Reset()                    { *m = PartitionInfo{} }
func (m *PartitionInfo) String() string            { return proto.CompactTextString(m) }
func (*PartitionInfo) ProtoMessage()               {}
func (*PartitionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PartitionInfo) GetMountPath() string {
	if m != nil {
		return m.MountPath
	}
	return ""
}

func (m *PartitionInfo) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PartitionInfo) GetFree() uint64 {
	if m != nil {
		return m.Free
	}
	return 0
}

func (m *PartitionInfo) GetFsType() string {
	if m != nil {
		return m.FsType
	}
	return ""
}

func (m *PartitionInfo) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

type HostInfo struct {
	HostName    string           `protobuf:"bytes,1,opt,name=HostName" json:"HostName,omitempty"`
	OsName      string           `protobuf:"bytes,2,opt,name=osName" json:"osName,omitempty"`
	OsVersion   string           `protobuf:"bytes,3,opt,name=osVersion" json:"osVersion,omitempty"`
	NumCores    uint32           `protobuf:"varint,4,opt,name=numCores" json:"numCores,omitempty"`
	FileSystems []*PartitionInfo `protobuf:"bytes,5,rep,name=fileSystems" json:"fileSystems,omitempty"`
}

func (m *HostInfo) Reset()                    { *m = HostInfo{} }
func (m *HostInfo) String() string            { return proto.CompactTextString(m) }
func (*HostInfo) ProtoMessage()               {}
func (*HostInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HostInfo) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *HostInfo) GetOsName() string {
	if m != nil {
		return m.OsName
	}
	return ""
}

func (m *HostInfo) GetOsVersion() string {
	if m != nil {
		return m.OsVersion
	}
	return ""
}

func (m *HostInfo) GetNumCores() uint32 {
	if m != nil {
		return m.NumCores
	}
	return 0
}

func (m *HostInfo) GetFileSystems() []*PartitionInfo {
	if m != nil {
		return m.FileSystems
	}
	return nil
}

type HealthInfo struct {
	TotalMemory     uint64  `protobuf:"varint,1,opt,name=totalMemory" json:"totalMemory,omitempty"`
	AvailableMemory uint64  `protobuf:"varint,2,opt,name=availableMemory" json:"availableMemory,omitempty"`
	CpuLoad1        float64 `protobuf:"fixed64,3,opt,name=cpuLoad1" json:"cpuLoad1,omitempty"`
	CpuLoad5        float64 `protobuf:"fixed64,4,opt,name=cpuLoad5" json:"cpuLoad5,omitempty"`
	CpuLoad15       float64 `protobuf:"fixed64,5,opt,name=cpuLoad15" json:"cpuLoad15,omitempty"`
}

func (m *HealthInfo) Reset()                    { *m = HealthInfo{} }
func (m *HealthInfo) String() string            { return proto.CompactTextString(m) }
func (*HealthInfo) ProtoMessage()               {}
func (*HealthInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HealthInfo) GetTotalMemory() uint64 {
	if m != nil {
		return m.TotalMemory
	}
	return 0
}

func (m *HealthInfo) GetAvailableMemory() uint64 {
	if m != nil {
		return m.AvailableMemory
	}
	return 0
}

func (m *HealthInfo) GetCpuLoad1() float64 {
	if m != nil {
		return m.CpuLoad1
	}
	return 0
}

func (m *HealthInfo) GetCpuLoad5() float64 {
	if m != nil {
		return m.CpuLoad5
	}
	return 0
}

func (m *HealthInfo) GetCpuLoad15() float64 {
	if m != nil {
		return m.CpuLoad15
	}
	return 0
}

func init() {
	proto.RegisterType((*PartitionInfo)(nil), "sysinfo.PartitionInfo")
	proto.RegisterType((*HostInfo)(nil), "sysinfo.HostInfo")
	proto.RegisterType((*HealthInfo)(nil), "sysinfo.HealthInfo")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xc9, 0xd6, 0x4d, 0x97, 0x32, 0x84, 0x1c, 0x46, 0x11, 0x0f, 0x65, 0xa7, 0x9e, 0x06,
	0x2a, 0x03, 0xef, 0x5e, 0x26, 0x38, 0x19, 0x51, 0xbc, 0x67, 0xdb, 0x2b, 0x0b, 0xb4, 0x7d, 0x25,
	0xc9, 0x06, 0xf5, 0xee, 0xbf, 0xe3, 0xc1, 0xbf, 0x50, 0xf2, 0x52, 0xd7, 0xea, 0xed, 0x7d, 0xbf,
	0xf7, 0xf8, 0xf8, 0xf2, 0x85, 0xc7, 0xae, 0xa9, 0xc1, 0x2e, 0x6a, 0x83, 0x0e, 0xc5, 0x85, 0x6d,
	0xac, 0xae, 0x72, 0x9c, 0x7f, 0x32, 0x3e, 0xdd, 0x28, 0xe3, 0xb4, 0xd3, 0x58, 0x3d, 0x55, 0x39,
	0x8a, 0x1b, 0x3e, 0x59, 0xe3, 0xb1, 0x72, 0x1b, 0xe5, 0x0e, 0x09, 0x4b, 0x59, 0x36, 0x91, 0x1d,
	0x10, 0x82, 0x47, 0x56, 0x7f, 0x40, 0x32, 0x48, 0x59, 0x16, 0x49, 0x9a, 0x3d, 0xcb, 0x0d, 0x40,
	0x32, 0x0c, 0xcc, 0xcf, 0x62, 0xc6, 0xc7, 0xb9, 0x7d, 0x6b, 0x6a, 0x48, 0x22, 0xb2, 0x68, 0x95,
	0xe7, 0x7b, 0x38, 0xe9, 0x1d, 0x24, 0xa3, 0xc0, 0x83, 0x9a, 0x7f, 0x33, 0x7e, 0xb9, 0x42, 0xeb,
	0x28, 0xc2, 0x75, 0x98, 0x5f, 0x54, 0x09, 0x6d, 0x82, 0xb3, 0xf6, 0x06, 0x68, 0x69, 0x33, 0x08,
	0x06, 0x41, 0xf9, 0xd8, 0x68, 0xdf, 0xc1, 0x58, 0x8d, 0x15, 0x25, 0x99, 0xc8, 0x0e, 0x78, 0xc7,
	0xea, 0x58, 0x3e, 0xa2, 0x01, 0x4b, 0x81, 0xa6, 0xf2, 0xac, 0xc5, 0x03, 0x8f, 0x73, 0x5d, 0xc0,
	0x6b, 0x63, 0x1d, 0x94, 0x36, 0x19, 0xa5, 0xc3, 0x2c, 0xbe, 0x9b, 0x2d, 0xda, 0x86, 0x16, 0x7f,
	0xda, 0x91, 0xfd, 0xd3, 0xf9, 0x17, 0xe3, 0x7c, 0x05, 0xaa, 0x70, 0x07, 0x8a, 0x9d, 0xf2, 0xd8,
	0xa1, 0x53, 0xc5, 0x1a, 0x4a, 0x34, 0x0d, 0x25, 0x8f, 0x64, 0x1f, 0x89, 0x8c, 0x5f, 0xa9, 0x93,
	0xd2, 0x85, 0xda, 0x16, 0xd0, 0x5e, 0x85, 0x22, 0xff, 0x63, 0x1f, 0x78, 0x57, 0x1f, 0x9f, 0x51,
	0xed, 0x6f, 0xe9, 0x35, 0x4c, 0x9e, 0x75, 0x6f, 0xb7, 0xa4, 0xc7, 0x74, 0xbb, 0xa5, 0xaf, 0xe1,
	0xf7, 0x6e, 0x49, 0x15, 0x33, 0xd9, 0x81, 0xed, 0x98, 0x7e, 0xff, 0xfe, 0x27, 0x00, 0x00, 0xff,
	0xff, 0xa1, 0x7a, 0x14, 0xbc, 0x0c, 0x02, 0x00, 0x00,
}
