// Code generated by protoc-gen-go. DO NOT EDIT.
// source: docker/dkr.proto

package docker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContainerInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Started              int64    `protobuf:"varint,3,opt,name=started,proto3" json:"started,omitempty"`
	Names                []string `protobuf:"bytes,4,rep,name=names,proto3" json:"names,omitempty"`
	Imageid              string   `protobuf:"bytes,5,opt,name=imageid,proto3" json:"imageid,omitempty"`
	InternalCommand      string   `protobuf:"bytes,6,opt,name=internalCommand,proto3" json:"internalCommand,omitempty"`
	State                string   `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Status               string   `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerInfo) Reset()         { *m = ContainerInfo{} }
func (m *ContainerInfo) String() string { return proto.CompactTextString(m) }
func (*ContainerInfo) ProtoMessage()    {}
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_025ca2bea7fc011c, []int{0}
}

func (m *ContainerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerInfo.Unmarshal(m, b)
}
func (m *ContainerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerInfo.Marshal(b, m, deterministic)
}
func (m *ContainerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerInfo.Merge(m, src)
}
func (m *ContainerInfo) XXX_Size() int {
	return xxx_messageInfo_ContainerInfo.Size(m)
}
func (m *ContainerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerInfo proto.InternalMessageInfo

func (m *ContainerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ContainerInfo) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ContainerInfo) GetStarted() int64 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *ContainerInfo) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *ContainerInfo) GetImageid() string {
	if m != nil {
		return m.Imageid
	}
	return ""
}

func (m *ContainerInfo) GetInternalCommand() string {
	if m != nil {
		return m.InternalCommand
	}
	return ""
}

func (m *ContainerInfo) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ContainerInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*ContainerInfo)(nil), "docker.ContainerInfo")
}

func init() { proto.RegisterFile("docker/dkr.proto", fileDescriptor_025ca2bea7fc011c) }

var fileDescriptor_025ca2bea7fc011c = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x41, 0x8e, 0xc2, 0x20,
	0x14, 0x86, 0x43, 0x3b, 0xa5, 0x33, 0x24, 0x33, 0x63, 0x88, 0x31, 0x6f, 0xd9, 0xb8, 0xea, 0x4a,
	0x17, 0x1e, 0xa1, 0x2b, 0xb7, 0xbd, 0x01, 0x0a, 0x1a, 0x52, 0x79, 0x18, 0x78, 0x9e, 0xd5, 0xeb,
	0x18, 0x5e, 0xed, 0xc6, 0x1d, 0xdf, 0x97, 0x8f, 0x3f, 0xa0, 0x56, 0x36, 0x9e, 0x27, 0x97, 0xf6,
	0x76, 0x4a, 0xbb, 0x7b, 0x8a, 0x14, 0xb5, 0x9c, 0xcd, 0xf6, 0x29, 0xd4, 0xef, 0x10, 0x91, 0x8c,
	0x47, 0x97, 0x8e, 0x78, 0x89, 0xfa, 0x4f, 0x55, 0xde, 0x82, 0xe8, 0x44, 0xff, 0x33, 0x56, 0xde,
	0xea, 0xb5, 0x6a, 0x7c, 0x30, 0x57, 0x07, 0x15, 0xab, 0x19, 0x34, 0xa8, 0x36, 0x93, 0x49, 0xe4,
	0x2c, 0xd4, 0x9d, 0xe8, 0xeb, 0x71, 0xc1, 0xd2, 0xa3, 0x09, 0x2e, 0xc3, 0x57, 0x57, 0x97, 0x9e,
	0xa1, 0xf4, 0x7c, 0xd1, 0x5b, 0x68, 0x78, 0x67, 0x41, 0xdd, 0xab, 0x7f, 0x8f, 0xe4, 0x12, 0x9a,
	0xdb, 0x10, 0x43, 0x30, 0x68, 0x41, 0x72, 0xf1, 0xa9, 0xcb, 0x72, 0x26, 0x43, 0x0e, 0xda, 0xf9,
	0x25, 0x0c, 0x7a, 0xa3, 0x64, 0x39, 0x3c, 0x32, 0x7c, 0xb3, 0x7e, 0xd3, 0x49, 0xf2, 0x47, 0x0f,
	0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x2c, 0x46, 0xc6, 0xfc, 0x00, 0x00, 0x00,
}
