name: build library

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPROXY: "https://goproxy.io,https://goproxy.dev,direct"
      CI: "1"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'
      - name: Check License Header
        uses: apache/skywalking-eyes/header@0.4.0
      - name: Check Dependencies' License
        uses: apache/skywalking-eyes/dependency@0.4.0
      - name: List files in the repository
        run: |
          go version
          ls ${{ github.workspace }}
      - name: get dependencies
        run: go get ./...
      - name: check vet status
        run: go vet $(go list ./... | grep -v /vendor/)
      - name: build all
        run: go build -race ./...
      - name: test all
        run: go test -v ./... -coverprofile .golang-coverage-report.txt -race $(go list ./... | grep -v /vendor/)
