name: build library

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPROXY: "https://goproxy.io,https://goproxy.dev,direct"
      CI: "1"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'
      - name: List files in the repository
        run: |
          go version
          ls ${{ github.workspace }}
      - name: get dependencies
        run: go get ./...
      - name: check vet status
        run: go vet $(go list ./... | grep -v /vendor/)
      - name: build all
        run: go build -race ./...
      - name: test all
        run: go test -v ./... -coverprofile .golang-coverage-report.txt -race $(go list ./... | grep -v /vendor/)
      # Download and invoke cyclonedx-gomod in a single step
      - name: Generate SBOM
        uses: CycloneDX/gh-gomod-generate-sbom@v1.1.0
        with:
          version: v1
          args: mod -licenses -json -output bom.json
