name: test licenses

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  test-licenses:
    name: testing licenses
    runs-on: ubuntu-latest
    env:
      GOPROXY: "https://goproxy.io,https://goproxy.dev,direct"
      CI: "1"
    steps:
      - name: Check out repository code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.5.0
      # - name: Check Dependencies' License
      #   uses: apache/skywalking-eyes/dependency@v0.5.0
